server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: business-service
          uri: lb://business-service
          predicates:
            - Path=/businesses/**
        - id: communication-service
          uri: lb://communication-service
          predicates:
            - Path=/communications/**
	- id: security-service
	  uri: lb://security-service
	  predicates:
	    - Path=/securities/**